In [4]:
import pandas as pd 
import numpy as np
from pathlib import Path

In [ ]:
caminho = Path("../data/raw/MICRODADOS_ENEM_1998.csv")
df98 = pd.read_csv(caminho)
print(df98.head())

C:\Users\tomas\OneDrive\Desktop\DStrabalho\data\raw\MICRODADOS_ENEM_1998.csv
True
  NU_INSCRICAO;NU_ANO;TP_FAIXA_ETARIA;TP_SEXO;CO_MUNICIPIO_RESIDENCIA;NO_MUNICIPIO_RESIDENCIA;CO_UF_RESIDENCIA;SG_UF_RESIDENCIA;TP_PRESENCA;CO_PROVA;VL_PERC_COMP1;VL_PERC_COMP2;VL_PERC_COMP3;VL_PERC_COMP4;VL_PERC_COMP5;NU_NOTA_OBJETIVA;TX_RESPOSTAS_OBJETIVA;TX_GABARITO_OBJETIVA;TP_STATUS_REDACAO;NU_NOTA_COMP1;NU_NOTA_COMP2;NU_NOTA_COMP3;NU_NOTA_COMP4;NU_NOTA_COMP5;NU_NOTA_REDACAO;IN_QSE;Q1;Q2;Q3;Q4;Q5;Q6;Q7;Q8;Q9;Q10;Q11;Q12;Q13;Q14;Q15;Q16;Q17;Q18;Q19;Q20;Q21;Q22;Q23;Q24;Q25;Q26;Q27;Q28;Q29;Q30;Q31;Q32;Q33;Q34;Q35;Q36;Q37;Q38;Q39;Q40;Q41;Q42;Q43;Q44;Q45;Q46;Q47;Q48;Q49;Q50;Q51;Q52;Q53;Q54;Q55;Q56;Q57;Q58;Q59;Q60;Q61;Q62;Q63;Q64;Q65;Q66;Q67;Q68;Q69;Q70;Q71;Q72;Q73;Q74;Q75;Q76;Q77;Q78;Q79;Q80;Q81;Q82;Q83;Q84;Q85;Q86;Q87;Q88;Q89;Q90;Q91;Q92;Q93;Q94;Q95;Q96;Q97;Q98;Q99;Q100;Q101;Q102;Q103;Q104;Q105;Q106;Q107;Q108;Q109;Q110;Q111;Q112;Q113;Q114;Q115;Q116;Q117;Q118;Q119;Q120;Q121;Q122;Q123;Q124;Q125;Q126;Q127;Q128;Q129;Q130;Q131;Q132;Q133;Q134;Q135;Q136;Q137
0  1;1998;4;F;2408003;MOSSORO;24;RN;1;B;43.3;33.3...
1  2;1998;2;F;2401453;BARAUNA;24;RN;1;B;23.3;31;2...
2  3;1998;3;M;2408003;MOSSORO;24;RN;1;Z;46.7;50;5...
3  4;1998;3;M;2408003;MOSSORO;24;RN;1;G;30;40.5;4...
4  5;1998;6;M;2413102;SENADOR ELOI DE SOUZA;24;RN...

In [15]:
caminho2 = Path("../data/raw/MICRODADOS_ENEM_2001.csv")
caminho3 = Path("../data/raw/MICRODADOS_ENEM_2002.csv")
print(caminho2.resolve())
print(caminho2.is_file())
df2 = pd.read_csv(caminho2)
df3 = pd.read_csv(caminho3)
df2.head()

C:\Users\tomas\OneDrive\Desktop\DStrabalho\data\raw\MICRODADOS_ENEM_2001.csv
True

  NU_INSCRICAO;NU_ANO;TP_FAIXA_ETARIA;TP_SEXO;CO_MUNICIPIO_RESIDENCIA;NO_MUNICIPIO_RESIDENCIA;CO_UF_RESIDENCIA;SG_UF_RESIDENCIA;TP_ST_CONCLUSAO;CO_MUNICIPIO_ESC;NO_MUNICIPIO_ESC;CO_UF_ESC;SG_UF_ESC;TP_DEPENDENCIA_ADM_ESC;TP_LOCALIZACAO_ESC;TP_SIT_FUNC_ESC;TP_PRESENCA;CO_PROVA;VL_PERC_COMP1;VL_PERC_COMP2;VL_PERC_COMP3;VL_PERC_COMP4;VL_PERC_COMP5;NU_NOTA_OBJETIVA;TX_RESPOSTAS_OBJETIVA;TX_GABARITO_OBJETIVA;TP_STATUS_REDACAO;NU_NOTA_COMP1;NU_NOTA_COMP2;NU_NOTA_COMP3;NU_NOTA_COMP4;NU_NOTA_COMP5;NU_NOTA_REDACAO;IN_QSE;Q1;Q2;Q3;Q4;Q5;Q6_1;Q6_2;Q6_3;Q6_4;Q6_5;Q6_6;Q6_7;Q6_8;Q7;Q8;Q9;Q10;Q11;Q12;Q13;Q14;Q15;Q16_1;Q16_2;Q16_3;Q16_4;Q16_5;Q16_6;Q16_7;Q16_8;Q16_9;Q16_10;Q17_1;Q17_2;Q17_3;Q17_4;Q17_5;Q18;Q19;Q20;Q21;Q22;Q23;Q24;Q25;Q26;Q27;Q28;Q29;Q30_1;Q30_2;Q30_3;Q30_4;Q31;Q32;Q33_1;Q33_2;Q33_3;Q33_4;Q33_5;Q33_6;Q33_7;Q34_1;Q34_2;Q34_3;Q34_4;Q34_5;Q34_6;Q34_7;Q35;Q36;Q37;Q38;Q39;Q40;Q41;Q42_1;Q42_2;Q42_3;Q42_4;Q42_5;Q43_1;Q43_2;Q43_3;Q43_4;Q43_5;Q44_1;Q44_2;Q44_3;Q44_4;Q44_5;Q44_6;Q44_7;Q44_8;Q44_9;Q44_10;Q44_11;Q44_12;Q44_13;Q44_14;Q44_15;Q44_16;Q45_1;Q45_2;Q45_3;Q45_4;Q45_5;Q45_6;Q45_7;Q45_8;Q46;Q47_1;Q47_2;Q47_3;Q47_4;Q47_5;Q47_6;Q47_7;Q48_1;Q48_2;Q48_3;Q48_4;Q49;Q50_1;Q50_2;Q50_3;Q50_4;Q50_5;Q50_6;Q50_7;Q50_8;Q50_9;Q50_10;Q50_11;Q50_12;Q50_13;Q50_14;Q51;Q52;Q53;Q54;Q55;Q56_1;Q56_2;Q56_3;Q56_4;Q56_5;Q56_6;Q56_7;Q56_8;Q57;Q58;Q59_1;Q59_2;Q59_3;Q59_4;Q59_5;Q59_6;Q59_7;Q60_1;Q60_2;Q60_3;Q60_4;Q60_5;Q60_6;Q60_7;Q60_8;Q60_9;Q60_10;Q61_1;Q61_2;Q62_1;Q62_2;Q63_1;Q63_2;Q64_1;Q64_2;Q64_3;Q64_4;Q64_5;Q64_6;Q64_7;Q64_8;Q64_9;Q64_10;Q64_11;Q64_12;Q64_13;Q65_1;Q65_2;Q65_3;Q65_4;Q65_5;Q65_6;Q65_7;Q65_8;Q65_9;Q65_10;Q65_11;Q65_12;Q66_1;Q66_2;Q66_3;Q66_4;Q66_5;Q66_6;Q66_7;Q67;Q68;Q69;Q70_1;Q70_2;Q70_3;Q70_4;Q70_5;Q70_6;Q70_7;Q70_8;Q71_1;Q71_2;Q71_3;Q71_4;Q72;Q73_1;Q73_2;Q73_3;Q73_4;Q73_5;Q73_6;Q74_1;Q74_2;Q74_3;Q74_4;Q74_5;Q74_6;Q74_7;Q75_1;Q75_2;Q75_3;Q75_4;Q75_5;Q75_6
0  9;2001;4;M;3549102;SAO JOAO DA BOA VISTA;35;SP...
1  11;2001;2;M;3510807;CASA BRANCA;35;SP;2;;;;;;;...
2  15;2001;3;M;3510807;CASA BRANCA;35;SP;2;;;;;;;...
3  18;2001;8;F;2311306;QUIXADA;23;CE;1;2311306;QU...
4  20;2001;7;F;2311306;QUIXADA;23;CE;1;2311306;QU...

In [20]:
dados2001_2002 = pd.concat([df2,df3], ignore_index=True)
dados2001_2002.to_csv("Dados2001_2002.csv",index = False)

In [21]:
caminho4 = Path("../data/raw/MICRODADOS_ENEM_2003.csv")
caminho5 = Path("../data/raw/MICRODADOS_ENEM_2004.csv")
print(caminho4.resolve())
print(caminho4.is_file())
df4 = pd.read_csv(caminho4)
df5 = pd.read_csv(caminho5)
df4.head()

C:\Users\tomas\OneDrive\Desktop\DStrabalho\data\raw\MICRODADOS_ENEM_2003.csv
True

  NU_INSCRICAO;NU_ANO;TP_FAIXA_ETARIA;TP_SEXO;CO_MUNICIPIO_RESIDENCIA;NO_MUNICIPIO_RESIDENCIA;CO_UF_RESIDENCIA;SG_UF_RESIDENCIA;TP_ST_CONCLUSAO;CO_MUNICIPIO_ESC;NO_MUNICIPIO_ESC;CO_UF_ESC;SG_UF_ESC;TP_DEPENDENCIA_ADM_ESC;TP_LOCALIZACAO_ESC;TP_SIT_FUNC_ESC;TP_PRESENCA;CO_PROVA;VL_PERC_COMP1;VL_PERC_COMP2;VL_PERC_COMP3;VL_PERC_COMP4;VL_PERC_COMP5;NU_NOTA_OBJETIVA;TX_RESPOSTAS_OBJETIVA;TX_GABARITO_OBJETIVA;TP_STATUS_REDACAO;NU_NOTA_COMP1;NU_NOTA_COMP2;NU_NOTA_COMP3;NU_NOTA_COMP4;NU_NOTA_COMP5;NU_NOTA_REDACAO;IN_QSE;Q1;Q2;Q3;Q4;Q5;Q6;Q7;Q8;Q9;Q10;Q11;Q12;Q13;Q14;Q15;Q16;Q17;Q18;Q19;Q20;Q21;Q22;Q23;Q24;Q25;Q26;Q27;Q28;Q29;Q30;Q31;Q32;Q33;Q34;Q35;Q36;Q37;Q38;Q39;Q40;Q41;Q42;Q43;Q44;Q45;Q46;Q47;Q48;Q49;Q50;Q51;Q52;Q53;Q54;Q55;Q56;Q57;Q58;Q59;Q60;Q61;Q62;Q63;Q64;Q65;Q66;Q67;Q68;Q69;Q70;Q71;Q72;Q73;Q74;Q75;Q76;Q77;Q78;Q79;Q80;Q81;Q82;Q83;Q84;Q85;Q86;Q87;Q88;Q89;Q90;Q91;Q92;Q93;Q94;Q95;Q96;Q97;Q98;Q99;Q100;Q101;Q102;Q103;Q104;Q105;Q106;Q107;Q108;Q109;Q110;Q111;Q112;Q113;Q114;Q115;Q116;Q117;Q118;Q119;Q120;Q121;Q122;Q123;Q124;Q125;Q126;Q127;Q128;Q129;Q130;Q131;Q132;Q133;Q134;Q135;Q136;Q137;Q138;Q139;Q140;Q141;Q142;Q143;Q144;Q145;Q146;Q147;Q148;Q149;Q150;Q151;Q152;Q153;Q154;Q155;Q156;Q157;Q158;Q159;Q160;Q161;Q162;Q163;Q164;Q165;Q166;Q167;Q168;Q169;Q170;Q171;Q172;Q173;Q174;Q175;Q176;Q177;Q178;Q179;Q180;Q181;Q182;Q183;Q184;Q185;Q186;Q187;Q188
0  1;2003;1;M;1505536;PARAUAPEBAS;15;PA;3;1505536...
1  2;2003;4;F;1505536;PARAUAPEBAS;15;PA;3;1505536...
2  3;2003;5;M;1505536;PARAUAPEBAS;15;PA;3;1505536...
3  4;2003;3;F;1505536;PARAUAPEBAS;15;PA;3;1505536...
4  5;2003;4;F;1505536;PARAUAPEBAS;15;PA;3;1505536...

In [22]:
dados2003_2004 = pd.concat([df4,df5], ignore_index=True)
dados2003_2004.to_csv("Dados2003_2004.csv",index = False)

In [24]:
df6 = pd.read_csv(caminho6, encoding="latin1", sep=";")
df7 = pd.read_csv(caminho7, encoding="latin1", sep=";")
df8 = pd.read_csv(caminho8, encoding="latin1", sep=";")
df9 = pd.read_csv(caminho9, encoding="latin1", sep=";")

print(df7.columns[:5].tolist())

print(caminho6.resolve())
print(caminho6.is_file())
df6 = pd.read_csv(caminho6)
df7 = pd.read_csv(caminho7)
df8 = pd.read_csv(caminho8)
df9 = pd.read_csv(caminho9)

df6.head()

C:\Users\tomas\AppData\Local\Temp\ipykernel_22552\4158906518.py:4: DtypeWarning: Columns (0: NO_MUNICIPIO_ESC, 1: SG_UF_ESC, 2: Q1, 3: Q2, 4: Q3, 5: Q4, 6: Q5, 7: Q6, 8: Q7, 9: Q8, 10: Q9, 11: Q10, 12: Q11, 13: Q12, 14: Q13, 15: Q14, 16: Q15, 17: Q16, 18: Q17, 19: Q18, 20: Q19, 21: Q20, 22: Q21, 23: Q22, 24: Q23, 25: Q24, 26: Q25, 27: Q26, 28: Q27, 29: Q28, 30: Q29, 31: Q30, 32: Q31, 33: Q32, 34: Q33, 35: Q34, 36: Q35, 37: Q36, 38: Q37, 39: Q38, 40: Q39, 41: Q40, 42: Q41, 43: Q42, 44: Q43, 45: Q44, 46: Q45, 47: Q46, 48: Q47, 49: Q48, 50: Q49, 51: Q50, 52: Q51, 53: Q52, 54: Q53, 55: Q54, 56: Q55, 57: Q56, 58: Q57, 59: Q58, 60: Q59, 61: Q60, 62: Q61, 63: Q62, 64: Q63, 65: Q64, 66: Q65, 67: Q66, 68: Q67, 69: Q68, 70: Q69, 71: Q70, 72: Q71, 73: Q72, 74: Q73, 75: Q74, 76: Q75, 77: Q76, 78: Q77, 79: Q78, 80: Q79, 81: Q80, 82: Q81, 83: Q82, 84: Q83, 85: Q84, 86: Q85, 87: Q86, 88: Q87, 89: Q88, 90: Q89, 91: Q90, 92: Q91, 93: Q92, 94: Q93, 95: Q94, 96: Q95, 97: Q96, 98: Q97, 99: Q98, 100: Q99, 101: Q100, 102: Q101, 103: Q102, 104: Q103, 105: Q104, 106: Q105, 107: Q106, 108: Q107, 109: Q108, 110: Q109, 111: Q110, 112: Q111, 113: Q112, 114: Q113, 115: Q114, 116: Q115, 117: Q116, 118: Q117, 119: Q118, 120: Q119, 121: Q120, 122: Q121, 123: Q122, 124: Q123, 125: Q124, 126: Q125, 127: Q126, 128: Q127, 129: Q128, 130: Q129, 131: Q130, 132: Q131, 133: Q132, 134: Q133, 135: Q134, 136: Q135, 137: Q136, 138: Q137, 139: Q138, 140: Q139, 141: Q140, 142: Q141, 143: Q142, 144: Q143, 145: Q144, 146: Q145, 147: Q146, 148: Q147, 149: Q148, 150: Q149, 151: Q150, 152: Q151, 153: Q152, 154: Q153, 155: Q154, 156: Q155, 157: Q156, 158: Q157, 159: Q158, 160: Q159, 161: Q160, 162: Q161, 163: Q162, 164: Q163, 165: Q164, 166: Q165, 167: Q166, 168: Q167, 169: Q168, 170: Q169, 171: Q170, 172: Q171, 173: Q172, 174: Q173, 175: Q174, 176: Q175, 177: Q176, 178: Q177, 179: Q178, 180: Q179, 181: Q180, 182: Q181, 183: Q182, 184: Q183, 185: Q184, 186: Q185, 187: Q186, 188: Q187, 189: Q188, 190: Q189, 191: Q190, 192: Q191, 193: Q192, 194: Q193, 195: Q194, 196: Q195, 197: Q196, 198: Q197, 199: Q198, 200: Q199, 201: Q200, 202: Q201, 203: Q202, 204: Q203, 205: Q204, 206: Q205, 207: Q206, 208: Q207, 209: Q208, 210: Q209, 211: Q210, 212: Q211, 213: Q212, 214: Q213, 215: Q214, 216: Q215, 217: Q216, 218: Q217, 219: Q218, 220: Q219, 221: Q220, 222: Q221, 223: Q222, 224: Q223) have mixed types. Specify dtype option on import or set low_memory=False.
  df9 = pd.read_csv(caminho9, encoding="latin1", sep=";")

['NU_INSCRICAO', 'NU_ANO', 'TP_FAIXA_ETARIA', 'TP_SEXO', 'CO_MUNICIPIO_RESIDENCIA']
C:\Users\tomas\OneDrive\Desktop\DStrabalho\data\raw\MICRODADOS_ENEM_2005.csv
True

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 12750: invalid start byte